'''AKHAINI(Shyama)
BABRAPUR(Chinta)
BABRAPUR(Shakuntla)
BACHAPAR(Chandrakanta)
BACHAPAR(Meera)
BACHAPAR(Santosh)
BACHAPAR(Vidyawati)
BADASARI(Indu Tiwari)
BAGHA(Sarita)
BAHERI (POONAM)
BAHERI(Saroj)
BANKATA(Gayatri)
BANKATA(Gudiya)
BELAHI(Meena)
BELAONA(Arti)
BHABHNAULI
BHUDADIH(Geeta)
BHUDADIH(Suman)
BICHIBOJH(Lalti)
BISHHAR(Mamta)
BISHHAR(pushpa)
Bhudadih
CHACHARI(Nilam)
CHACHARI(Urmila)
CHAKBAHADUN(Geeta)
CHAKBAHADUN(Munni)
CHAKJALALPUR(Seema)
CHAKJIYA(Punam)
CHAKMOTI(Reema)
CHAKRA(Sanjita)
CHAKUJIYAR(Panna)
CHAKUSHAULI(Asha)
CHAKUSHAULI(Sanju)
CHARWA BARWA(Dewanti)
CHARWA BARWA(Habibunisa)
CHARWA BARWA(Meena)
CHARWA BARWA(Sona Devi)
CHARWA BARWA(Tara)
CHITUPUR(Rajkumari)
CHOTIVISHAHAR(Manju)
Chakusraila (Sanju)
DAKINGANJ
DHADNSARA(Nilam)
DHANEJA(Rinku)
DHANEJA(Vijyanti)
DOBHWA(Lalsa)
DODHRA
DODHRA
Doghara (Seema)
Doghara(Neetu)
EKAIL(Gangotri)
EKAIL(Geeta)
FIROJPUR(Shailkumari)
FIROJPUR(Urmila)
Firozpur
GADMALPUR(Babita)
GADMALPUR(Manki)
GADMALPUR(Usha)
GAURAMADANPURA(Aarti)
GAURAMADANPURA(Vimla)
GAURI(Kiran)
GAURI(Omlata)
GAURI(Suman)
GAURNIYA(Mansha)
GODWARA(Indu Yadav)
GOPALPUR(Punam)
HARIPUR(Ambika)
HARIPUR(Sharda)
JAGDARA(Durgaji Tiwari)
JAGDARA(Tara)
JANUWAL(Geeta)
JANUWAL(Kismat)
JETHWAR(Durgawati)
JETHWAR(Sunanda)
JIMICHAK(phulwanti)
JOGESHARA(Munni)
KACHILA(Gyanti)
KADSAR(Gyanti)
KAITHAULI(Maya)
KAITHAULI(Radhika)
KALYADDEHRA(Chandrawati)
KALYADDEHRA(Sushila)
KHABASPUR(Nirmala)
KHADRSHARA(Anju)
KHADRSHARA(Savitri)
KHADRSHARA(Subhawati)
KHADRSHARA(Urmila)
KHAIRACHAK(Sangeeta)
KHEJURI P.S 1(Nisha)
KHEJURI P.S.2(Kanti)
KHEJURI(Usha)
KHEJURIP.S.2(Munni)
KHEJURIP.S.3(Sunita)
KHERACHAK(Suman)
KIKODARA(Manju)
KIKODARA(Tapasya)
KIKODHA(Meera)
KUDHI(Kunti)
LAKHNAPAR(Gayatri)
LEDUHI(Krishna)
MAHULANPAR(Meera)
MAHULANPAR(Rekha)
MASUMPUR(Afrin)
MASUMPUR(Amravati)
MASUMPUR(Saroj)
MASUMPUR(Sunaina)
MEULI(Manju)
MEULI(Nirmala)
MISHRAULI(Anjana)
MISHRAULI(Rinku)
MISHRAULI(Shubhawati)
MUDERA(Kavitaa)
MUJHI(Usha)
NAHILAPAR
NANHUL(Nayantara)
NANHUL(Usha)
PAHRAJPUR(Geeta)
PAKADI((Rita Singh)
PAKADI(Dropadi)
PAKADI(Kanaklata)
PAKADI(Rita Devi)
PAKADI(Urmila Gupta)
PAKADI(Urmila devi)
PAKADI(Usha)
PANDAH(Meena Rai)
PRASHADPUR(Gyanti)
PRASHADPUR(Sheela)
PUR(Asha)
PUR(Meera)
PUR(Mina)
PUR(Pinki)
PUR(Poonam)
PUR(Sanju)
PUR(Sunita)
RAKSHA(Meena)
RAMAPAR(Kaanti)
RAMAPAR(Umraavati)
RATSHI(Chinta)
RATSHI(Sheela)
RUPWAR(Reeta)
RUPWAR(Seema)
RUPWAR(Usha)
SAHULAI(Manju Yadav)
SAHULAI(Manju)
SAHULAI(Punam)
SAHULAI(Reeta)
SAHULAI(Sakuntla)
SAHULAI(Sunita)
SAHULAI(Sureman)
SAHULAI(Sureman)
SAKALPUR(Meera)
SAKALPURA(Asha)
SALEMPUR(Kiran)
SANDAWAPUR(Asha)
SANDAWAPUR(Meena)
SAPAHI(Nirmala)
SARANI(Janki)
SARAYA(Mamta)
SARAYA(Sandhya)
SARDAHI(Sarita)
SASNA AHLU(Phoolmati)
SASNA AHLU(Pushpa)
SATARSHAD(Archana)
SATRASHAD
SIDHAULI(Nirmalayati)
SIHORIYA
SIdHAULI(Mamta)
SONADIH
Sahulai
Sahulai
Saryan
Saryan
TANDAWA
UKCHI(Kalavti)
UKCHI(Vimala)
UMEDA(Rajkumari)
UMSHA(Sheela)
pandah(Sonamati)


from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = webdriver.ChromeOptions()
options.add_argument(r"--user-data-dir=C:\path\to\chrome\user\data") #e.g. C:\Users\You\AppData\Local\Google\Chrome\User Data
options.add_argument(r'--profile-directory=YourProfileDir') #e.g. Profile 3
driver = webdriver.Chrome(executable_path=r'C:\path\to\chromedriver.exe', options=options)
driver.get("https://www.google.co.in")



'''

visited=['Select a AWC', 'Aaripur Sarya Sunita', 'Aaripur Sarya Vimla', 'Abbaspur Aarti', 'Abbaspur Kiran', 'AKHAINI(Shyama)', 'BABRAPUR(Chinta)', 'BABRAPUR(Shakuntla)', 'BACHAPAR(Chandrakanta)', 'BACHAPAR(Meera)', 'BACHAPAR(Santosh)', 'BACHAPAR(Vidyawati)', 'BADASARI(Indu Tiwari)', 'BAGHA(Sarita)', 'BAHERI (POONAM)', 'BAHERI(Saroj)', 'BANKATA(Gayatri)', 'BANKATA(Gudiya)', 'BELAHI(Meena)', 'BELAONA(Arti)', 'BHABHNAULI(Champa)', 'BHUDADIH(Geeta)', 'BHUDADIH(Suman)', 'BICHIBOJH(Lalti)', 'BISHHAR(Mamta)', 'BISHHAR(pushpa)', 'CHACHARI(Nilam)', 'CHACHARI(Urmila)', 'CHAKBAHADUN(Geeta)', 'CHAKBAHADUN(Munni)', 'CHAKJALALPUR(Seema)', 'CHAKJIYA(Punam)', 'CHAKMOTI(Reema)', 'CHAKRA(Sanjita)', 'CHAKUJIYAR(Panna)', 'CHAKUSHAULI(Asha)', 'CHAKUSHAULI(Sanju)', 'CHARWA BARWA(Dewanti)', 'CHARWA BARWA(Habibunisa)', 'CHARWA BARWA(Meena)', 'CHARWA BARWA(Sona Devi)', 'CHARWA BARWA(Tara)', 'CHITUPUR(Rajkumari)', 'CHOTIVISHAHAR(Manju)', 'DAKINGANJ', 'DHADNSARA(Nilam)', 'DHANEJA(Rinku)', 'DHANEJA(Vijyanti)', 'DOBHWA(Lalsa)', 'Doghara (Seema)', 'Doghara(Neetu)', 'EKAIL(Gangotri)', 'EKAIL(Geeta)', 'FIROJPUR(Shailkumari)', 'FIROJPUR(Urmila)', 'GADMALPUR(Babita)', 'GADMALPUR(Manki)', 'GADMALPUR(Usha)', 'GAURAMADANPURA(Aarti)', 'GAURAMADANPURA(Vimla)', 'GAURI(Kiran)', 'GAURI(Omlata)', 'GAURI(Suman)', 'GAURNIYA(Mansha)', 'GODWARA(Indu Yadav)', 'GOPALPUR(Punam)', 'HARIPUR(Ambika)', 'HARIPUR(Sharda)', 'JAGDARA(Durgaji Tiwari)', 'JAGDARA(Tara)', 'JANUWAL(Geeta)', 'JANUWAL(Kismat)', 'JETHWAR(Durgawati)', 'JETHWAR(Sunanda)', 'JIMICHAK(phulwanti)', 'JOGESHARA(Munni)', 'KACHILA(Gyanti)', 'KADSAR(Gyanti)', 'KAITHAULI(Maya)', 'KAITHAULI(Radhika)', 'KALYADDEHRA(Chandrawati)', 'KALYADDEHRA(Sushila)', 'KHABASPUR(Nirmala)', 'KHADRSHARA(Anju)', 'KHADRSHARA(Savitri)', 'KHADRSHARA(Subhawati)', 'KHADRSHARA(Urmila)', 'KHAIRACHAK(Sangeeta)', 'KHEJURI P.S 1(Nisha)', 'KHEJURI P.S.2(Kanti)', 'KHEJURI(Usha)', 'KHEJURIP.S.2(Munni)', 'KHEJURIP.S.3(Sunita)', 'KHERACHAK(Suman)', 'KIKODARA(Manju)', 'KIKODARA(Tapasya)', 'KIKODHA(Meera)', 'KUDHI(Kunti)', 'LAKHNAPAR(Gayatri)', 'LEDUHI(Krishna)', 'MAHULANPAR(Meera)', 'MAHULANPAR(Rekha)', 'MASUMPUR(Afrin)', 'MASUMPUR(Amravati)', 'MASUMPUR(Saroj)', 'MASUMPUR(Sunaina)', 'MEULI(Manju)', 'MEULI(Nirmala)', 'MISHRAULI(Anjana)', 'MISHRAULI(Rinku)', 'MISHRAULI(Shubhawati)', 'MUDERA(Kavitaa)', 'MUJHI(Usha)', 'NAHILAPAR', 'NANHUL(Nayantara)', 'NANHUL(Usha)', 'PAHRAJPUR(Geeta)', 'PAKADI((Rita Singh)', 'PAKADI(Dropadi)', 'PAKADI(Kanaklata)', 'PAKADI(Rita Devi)', 'PAKADI(Urmila Gupta)', 'PAKADI(Urmila devi)', 'PAKADI(Usha)', 'PANDAH(Meena Rai)', 'PRASHADPUR(Gyanti)', 'PRASHADPUR(Sheela)', 'PUR(Asha)', 'PUR(Meera)', 'PUR(Mina)', 'PUR(Pinki)', 'PUR(Poonam)', 'PUR(Sanju)', 'PUR(Sunita)', 'RAKSHA(Meena)', 'RAMAPAR(Kaanti)', 'RAMAPAR(Umraavati)', 'RATSHI(Chinta)', 'RATSHI(Sheela)', 'RUPWAR(Reeta)', 'RUPWAR(Seema)', 'RUPWAR(Usha)', 'SAHULAI(M)(Sureman)', 'SAHULAI(Manju Yadav)', 'SAHULAI(Manju)', 'SAHULAI(Punam)', 'SAHULAI(Reeta)', 'SAHULAI(Sakuntla)', 'SAHULAI(Sunita)', 'SAHULAI(Sureman)', 'SAKALPUR(Meera)', 'SAKALPURA(Asha)', 'SALEMPUR(Kiran)', 'SANDAWAPUR(Asha)', 'SANDAWAPUR(Meena)', 'SAPAHI(Nirmala)', 'SARANI(Janki)', 'SARAYA(Mamta)', 'SARAYA(Sandhya)', 'SARDAHI(Sarita)', 'SASNA AHLU(Phoolmati)', 'SASNA AHLU(Pushpa)', 'SATARSHAD(Archana)', 'SIDHAULI(Nirmalayati)', 'SIHORIYA', 'SIdHAULI(Mamta)', 'SONADIH', 'TANDAWA', 'UKCHI(Kalavti)', 'UKCHI(Vimala)', 'UMEDA (Rajkumari)', 'UMEDA(Rajkumari)', 'USASHA(Sheela)', 'pandah(Sonamati)']